name = "Othello"
uuid = "321d9ce5-1115-4f63-8a97-4985e0e46a0d"
authors = ["Juven14s <rdjimadoum20@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
